<?php


namespace Hillel\Model;


use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function category()
    {
        return $this->belongsTo(category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(tag::class)->withTimestamps();
    }
    public function tagsAsString():string{
        $returnString ="";

        {foreach ($tags = $this->tags as $tag){
        $returnString .=$tag->title.", ";

            }
    }
        return $returnString;
    }
    public function delete()
    {
        $this->tags()->detach();

        return parent::delete(); // TODO: Change the autogenerated stub
    }


}