<?php


namespace Hillel\Model;


use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }
    public function tagsAsString():string{
        $returnString ="";

        {foreach ($tags = $this->tags as $tag){
        $returnString .=$tag->title.", ";

            }
    }
        return $returnString;
    }
    public function tagsAsArea(){
        $returnArea =array();
        foreach ($tags = $this->tags as $tag){
        $returnArea[] = $tag->id;

        }
       // var_dump($returnArea);
        return $returnArea;
    }
    public function delete()
    {
        $this->tags()->detach();

        return parent::delete(); // TODO: Change the autogenerated stub
    }


}